In [66]:
import torch

In [67]:
# method 1
x = torch.randn(3, 4, requires_grad=True)
x

tensor([[ 1.2602,  1.1471, -0.0381,  1.2928],
        [ 0.5844, -3.7446, -0.8877,  0.3014],
        [ 0.2620, -0.3927,  1.4484, -0.5490]], requires_grad=True)

In [68]:
# method 2
x = torch.randn(3, 4)
x.requires_grad = True
x

tensor([[ 2.0403, -0.5024,  0.2715, -2.1587],
        [-0.0223, -1.3281, -1.6920,  0.5831],
        [ 0.5939,  0.6695, -0.6446,  0.7672]], requires_grad=True)

In [69]:
b = torch.randn(3, 4, requires_grad=True)
b

tensor([[-0.4283,  0.5944, -0.0325,  0.0829],
        [-0.3373, -1.6346,  0.9554, -1.6942],
        [-0.1893, -0.3159, -0.2168, -0.7246]], requires_grad=True)

In [70]:
t = x + b
t

tensor([[ 1.6120,  0.0920,  0.2390, -2.0758],
        [-0.3596, -2.9627, -0.7366, -1.1111],
        [ 0.4046,  0.3536, -0.8614,  0.0426]], grad_fn=<AddBackward0>)

In [71]:
y = t.sum()
y

tensor(-5.3635, grad_fn=<SumBackward0>)

In [72]:
y.backward()

In [73]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
x.requires_grad, b.requires_grad, t.requires_grad

(True, True, True)

In [75]:
x = torch.rand(1)
b = torch.rand(1, requires_grad=True)
w = torch.rand(1, requires_grad=True)
y = w * x
z = y + b

In [76]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad

(False, True, True, True)

In [77]:
x.is_leaf, w.is_leaf, b.is_leaf, y.is_leaf, z.is_leaf

(True, True, True, False, False)

In [82]:
z.backward(retain_graph=True)

In [83]:
w.grad

tensor([1.1844])

In [84]:
b.grad

tensor([2.])