In [2]:
import torch


torch.__version__

'1.13.0'

In [5]:
x = torch.empty(5, 3)
x

tensor([[-1.4379e-35,  5.3810e-43, -1.4379e-35],
        [ 5.3810e-43, -1.4379e-35,  5.3810e-43],
        [-1.4379e-35,  5.3810e-43, -1.4379e-35],
        [ 5.3810e-43, -1.4379e-35,  5.3810e-43],
        [-1.4379e-35,  5.3810e-43, -1.4379e-35]])

In [6]:
x = torch.rand(5, 3)
x

tensor([[0.4748, 0.1309, 0.9365],
        [0.9221, 0.3333, 0.0544],
        [0.9780, 0.4985, 0.3394],
        [0.9249, 0.7939, 0.2377],
        [0.3498, 0.5093, 0.6431]])

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [15]:
x = x.new_ones(5, 3, dtype=torch.double)
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.3698,  0.5935,  0.6025],
        [-1.1291, -0.1057, -0.1708],
        [-1.1710, -2.4383,  0.2945],
        [-0.1116,  0.3720,  1.9553],
        [ 0.2466,  0.0198, -1.1760]])

In [13]:
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5, 3)
x + y

tensor([[ 0.4713,  1.5303,  0.6084],
        [-0.3471,  0.1255,  0.6959],
        [-0.7181, -1.5075,  1.1814],
        [ 0.7806,  0.5250,  2.7135],
        [ 0.6549,  0.3485, -0.4412]])

In [17]:
torch.add(x, y)

tensor([[ 0.4713,  1.5303,  0.6084],
        [-0.3471,  0.1255,  0.6959],
        [-0.7181, -1.5075,  1.1814],
        [ 0.7806,  0.5250,  2.7135],
        [ 0.6549,  0.3485, -0.4412]])

In [20]:
print(x)
print(x[:, 0])

tensor([[-0.3698,  0.5935,  0.6025],
        [-1.1291, -0.1057, -0.1708],
        [-1.1710, -2.4383,  0.2945],
        [-0.1116,  0.3720,  1.9553],
        [ 0.2466,  0.0198, -1.1760]])
tensor([-0.3698, -1.1291, -1.1710, -0.1116,  0.2466])


In [24]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
# -1 means auto compute the parameter
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.2726, -0.4043,  0.6940, -0.7451],
        [-0.9207,  0.1932, -0.4311,  1.3665],
        [-0.4346, -1.0982, -0.3426, -1.6440],
        [-0.0437, -0.4718, -0.3156, -0.6642]])
tensor([ 0.2726, -0.4043,  0.6940, -0.7451, -0.9207,  0.1932, -0.4311,  1.3665,
        -0.4346, -1.0982, -0.3426, -1.6440, -0.0437, -0.4718, -0.3156, -0.6642])
tensor([[ 0.2726, -0.4043,  0.6940, -0.7451, -0.9207,  0.1932, -0.4311,  1.3665],
        [-0.4346, -1.0982, -0.3426, -1.6440, -0.0437, -0.4718, -0.3156, -0.6642]])


In [25]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)