# Linear Algebra

In [2]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [6]:
x = torch.arange(4)
print(x)
print(len(x))
print(x.shape)
print(x[3])

tensor([0, 1, 2, 3])
4
torch.Size([4])
tensor(3)


In [8]:
a = torch.arange(20).reshape(5, 4)
print(a)
print(a.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [10]:
a = torch.arange(24).reshape(2, 3, 4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
a = 2
x = torch.arange(24).reshape(2, 3, 4)
a + x, (a + x).shape, a * x, (a * x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [17]:
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [18]:
x_sum_axis0 = x.sum(axis=0)
x_sum_axis0, x_sum_axis0.shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [20]:
x_sum_axis1 = x.sum(axis=1)
x_sum_axis1, x_sum_axis1.shape

(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [22]:
x_sum_axis01 = x.sum(axis=[0, 1])
x_sum_axis01, x_sum_axis01.shape

(tensor([60, 66, 72, 78]), torch.Size([4]))

In [25]:
x_sum_axis1 = x.sum(axis=1, keepdims=True)
x_sum_axis1, x_sum_axis1.shape

(tensor([[[12, 15, 18, 21]],
 
         [[48, 51, 54, 57]]]),
 torch.Size([2, 1, 4]))

In [32]:
x = torch.arange(4.0)
y = torch.ones(4, dtype=torch.float32)
print(x, y, torch.dot(x, y))
print(torch.sum(x * y))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor(6.)
