In [37]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [38]:
x.requires_grad_(True)  # x = torch.arange(4.0, requires_grad=True)
x.grad  # default is None

In [39]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [40]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [41]:
x.grad == 4 * x

tensor([True, True, True, True])

In [42]:
# pytorch 会累积梯度，需要清除前面的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [43]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [44]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [45]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [59]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(True)