In [12]:
import tensorflow as tf
import numpy as np

In [13]:
X = np.array([[0, 1, 2], [3, 4, 5]])
Y = tf.cast(X, tf.float32)

In [14]:
X, Y

(array([[0, 1, 2],
        [3, 4, 5]]),
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32)>)

In [19]:
mean_all = tf.reduce_mean(Y, keepdims=True)
print(mean_all)
mean_0 = tf.reduce_mean(Y, axis=0)
print(mean_0)
mean_1 = tf.reduce_mean(Y, axis=1)
print(mean_1)
mean__1 = tf.reduce_mean(Y, axis=-1)
print(mean__1)

tf.Tensor([[2.5]], shape=(1, 1), dtype=float32)
tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
tf.Tensor([1. 4.], shape=(2,), dtype=float32)
tf.Tensor([1. 4.], shape=(2,), dtype=float32)
